services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
#      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin 
      POSTGRES_USER: admin

